CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO business_types (
    id,
    group_name,
    label,
    default_bep_months,
    default_capital,
    recommended_property_types,
    recommended_placement,
    min_size_sqm,
    max_size_sqm,
    min_floors,
    max_floors,
    recommended_facilities,
    recommended_landmarks
) VALUES
(
    gen_random_uuid(),
    'F&B (Food & Beverages)',
    'Full-Service Restaurant',
    12,
    60000000.00,
    '["shophouse", "mall-shop", "food-court-counter"]'::jsonb,
    'indoor',
    30.00,
    100.00,
    1,
    2,
    '["power", "high-power", "water", "drainage", "grease-trap", "ventilation", "air-conditioner", "seating", "toilet", "parking", "trash-area"]'::jsonb,
    '["office", "market", "residential", "culinary-center"]'::jsonb
),
(
    gen_random_uuid(),
    'F&B (Food & Beverages)',
    'Coffee Shop & Cafe',
    9,
    35000000.00,
    '["shophouse", "mall-island", "garage-driveway"]'::jsonb,
    'indoor',
    12.00,
    40.00,
    1,
    1,
    '["power", "high-power", "water", "drainage", "ventilation", "wifi", "seating", "toilet", "parking"]'::jsonb,
    '["office", "campus", "residential", "transit-station"]'::jsonb
),
(
    gen_random_uuid(),
    'F&B (Food & Beverages)',
    'Bakery & Pastry Shop',
    9,
    30000000.00,
    '["mall-shop", "shophouse", "street-kiosk"]'::jsonb,
    'indoor',
    10.00,
    30.00,
    1,
    1,
    '["power", "high-power", "water", "ventilation", "air-conditioner", "storage", "display-case", "toilet"]'::jsonb,
    '["residential", "school", "market", "transit-station"]'::jsonb
),
(
    gen_random_uuid(),
    'F&B (Food & Beverages)',
    'Quick-Service / Fast Food',
    8,
    25000000.00,
    '["food-court-counter", "street-kiosk", "shophouse"]'::jsonb,
    'semi-outdoor',
    8.00,
    25.00,
    1,
    1,
    '["power", "water", "drainage", "grease-trap", "ventilation", "trash-area", "parking"]'::jsonb,
    '["campus", "office", "market", "culinary-center"]'::jsonb
),
(
    gen_random_uuid(),
    'F&B (Food & Beverages)',
    'Beverage & Snack Kiosk',
    4,
    10000000.00,
    '["mall-island", "street-kiosk", "food-court-counter"]'::jsonb,
    'semi-outdoor',
    4.00,
    12.00,
    1,
    1,
    '["power", "water", "drainage", "trash-area", "display-case"]'::jsonb,
    '["campus", "school", "residential", "transit-station", "transit-bus"]'::jsonb
),
(
    gen_random_uuid(),
    'Retail & Commerce',
    'Mini Market & Convenience Store',
    12,
    60000000.00,
    '["shophouse", "mall-shop"]'::jsonb,
    'indoor',
    40.00,
    100.00,
    1,
    2,
    '["power", "high-power", "water", "air-conditioner", "storage", "security", "cctv", "parking"]'::jsonb,
    '["residential", "office", "gas-station", "healthcare"]'::jsonb
),
(
    gen_random_uuid(),
    'Retail & Commerce',
    'Fashion & Apparel Boutique',
    10,
    40000000.00,
    '["traditional-market", "mall-shop", "shophouse"]'::jsonb,
    'indoor',
    8.00,
    35.00,
    1,
    1,
    '["power", "air-conditioner", "display-case", "storage", "security", "wifi"]'::jsonb,
    '["market", "office", "campus"]'::jsonb
),
(
    gen_random_uuid(),
    'Retail & Commerce',
    'General Retail & Hobby Store',
    9,
    25000000.00,
    '["traditional-market", "mall-island", "street-kiosk"]'::jsonb,
    'indoor',
    6.00,
    20.00,
    1,
    1,
    '["power", "display-case", "storage", "security", "cctv"]'::jsonb,
    '["residential", "market", "school"]'::jsonb
),
(
    gen_random_uuid(),
    'Services',
    'Beauty Salon & Barbershop',
    10,
    30000000.00,
    '["shophouse", "garage-driveway", "mall-shop"]'::jsonb,
    'indoor',
    15.00,
    45.00,
    1,
    1,
    '["power", "water", "drainage", "air-conditioner", "seating", "toilet", "parking"]'::jsonb,
    '["residential", "office", "campus"]'::jsonb
),
(
    gen_random_uuid(),
    'Services',
    'Service & Repair Shop',
    8,
    20000000.00,
    '["shophouse", "street-kiosk", "garage-driveway"]'::jsonb,
    'semi-outdoor',
    12.00,
    30.00,
    1,
    1,
    '["power", "high-power", "water", "storage", "parking"]'::jsonb,
    '["residential", "office", "gas-station"]'::jsonb
),
(
    gen_random_uuid(),
    'Services',
    'Professional Office & Agency',
    12,
    45000000.00,
    '["shophouse", "mall-shop"]'::jsonb,
    'indoor',
    20.00,
    60.00,
    1,
    2,
    '["power", "high-power", "wifi", "air-conditioner", "security", "toilet", "parking"]'::jsonb,
    '["office", "market", "government"]'::jsonb
),
(
    gen_random_uuid(),
    'Services',
    'Education & Studio Space',
    12,
    35000000.00,
    '["shophouse", "garage-driveway"]'::jsonb,
    'indoor',
    25.00,
    60.00,
    1,
    2,
    '["power", "water", "air-conditioner", "wifi", "seating", "toilet", "security", "parking"]'::jsonb,
    '["school", "campus", "residential"]'::jsonb
);