#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit checks..."

# 1. Format & Vet Code
go fmt ./... && go vet ./... || exit 1

# 2. Re-generate Wire Dependency Injection
make wire || exit 1

# 3. Test Build App (Memastikan tidak ada compile error)
go build -o /dev/null ./cmd/api || exit 1

echo "Pre-commit checks passed!"